## 1. Cargar los datos.

In [18]:
import pandas as pd
import numpy as np

data = {
    "nombre":  ["Ana", "Luis", "luis", " María ", "Pedro", "Ana", "sofía"],
    "edad":    [25, 32, 32, "veintiocho", 150, 25, np.nan],
    "salario": [15000, 22000, 22000, 18500, 999999, 15000, np.nan],
    "ciudad":  ["Culiacán", "Mazatlán", "Mazatlán", "culiacán", np.nan, "Culiacán", "Los Mochis"],
    "fecha":   ["2024-01-15", "2024/03/20", "2024/03/20", "15-04-2024", "2024-05-10", "2024-01-15", "2024-06-01"],
}

df = pd.DataFrame(data)
print(df)
print("\nInfo general:")
print(df.info())

    nombre        edad   salario      ciudad       fecha
0      Ana          25   15000.0    Culiacán  2024-01-15
1     Luis          32   22000.0    Mazatlán  2024/03/20
2     luis          32   22000.0    Mazatlán  2024/03/20
3   María   veintiocho   18500.0    culiacán  15-04-2024
4    Pedro         150  999999.0         NaN  2024-05-10
5      Ana          25   15000.0    Culiacán  2024-01-15
6    sofía         NaN       NaN  Los Mochis  2024-06-01

Info general:
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   7 non-null      str
 1   edad     6 non-null      object
 2   salario  6 non-null      float64
 3   ciudad   6 non-null      str
 4   fecha    7 non-null      str
dtypes: float64(1), object(1), str(3)
memory usage: 412.0+ bytes
None

In [19]:
df

    nombre        edad   salario      ciudad       fecha
0      Ana          25   15000.0    Culiacán  2024-01-15
1     Luis          32   22000.0    Mazatlán  2024/03/20
2     luis          32   22000.0    Mazatlán  2024/03/20
3   María   veintiocho   18500.0    culiacán  15-04-2024
4    Pedro         150  999999.0         NaN  2024-05-10
5      Ana          25   15000.0    Culiacán  2024-01-15
6    sofía         NaN       NaN  Los Mochis  2024-06-01

In [ ]:
Limpieza de datos
Duplicados
Manejo de valores nulos
Correcciones de errores en datos

## 2. Duplicados

In [20]:
print("Duplicados encontrados:", df.duplicated().sum())
print(df[df.duplicated(keep=False)])  # muestra todos los duplicados

Duplicados encontrados: 1
  nombre edad  salario    ciudad       fecha
0    Ana   25  15000.0  Culiacán  2024-01-15
5    Ana   25  15000.0  Culiacán  2024-01-15

## 3. Eliminar duplicados (conserva el primero)

In [22]:
df_clean = df.drop_duplicates()

## 4. Duplicados parciales: mismo nombre sin importar mayúsculas.

Normalizar nombre , Unificar mayúsculas/minúsculas — decidir una convención y aplicarla a todo:

.str.lower() → "ana" (útil para comparar)  
.str.upper() → "ANA"  
.str.title() → "Ana García" (la más legible para nombres)  
.str.capitalize() → "Ana garcía" (solo la primera letra del string)  
  
Colapsar espacios internos — "Luis  Alberto" (doble espacio) → "Luis Alberto" con .str.replace(r"\s+", " ", regex=True)

In [36]:


df_clean["nombre_norm"] = df_clean["nombre"].str.strip().str.lower()
dupes_nombre = df_clean.duplicated(subset="nombre_norm", keep=False)
print("\nDuplicados por nombre (normalizado):")
print(df_clean[dupes_nombre])

Duplicados por nombre (normalizado):
Empty DataFrame
Columns: [nombre, edad, salario, ciudad, fecha, nombre_norm]
Index: []

## 5.Eliminar duplicados parciales

In [37]:
df_clean = df_clean.drop_duplicates(subset="nombre_norm").drop(columns=["nombre_norm"])

print(f"\nFilas originales: {len(df)} → Después: {len(df_clean)}")

Filas originales: 7 → Después: 5

## 6.Imprime Nulos por columna

In [38]:
print(df.isnull().sum())          
print(df.isnull().sum().sum())

nombre     0
edad       1
salario    1
ciudad     1
fecha      0
dtype: int64
3

##  7.Ver filas con cualquier nulo

In [39]:
print(df[df.isnull().any(axis=1)])

  nombre edad   salario      ciudad       fecha
4  Pedro  150  999999.0         NaN  2024-05-10
6  sofía  NaN       NaN  Los Mochis  2024-06-01

## 8.Elimina filas con Nulos!

In [40]:
df_sin_nulos = df.dropna()

## 9.Ayuda para ver opciones

In [41]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: Axis = 0,
    how: AnyAll | lib.NoDefault = <no_default>,
    thresh: int | lib.NoDefault = <no_default>,
    subset: IndexLabel | AnyArrayLike | None = None,
    inplace: bool = False,
    ignore_index: bool = False
) -> DataFrame | None method of pandas.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or iterable of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "name": ["Alfred", "Batman", "Catwoman"],
    ...         "toy": [np.nan, "Batmobile", "Bullwhip"],
    ...         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    ...     }
    ... )
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis="columns")
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how="all")
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=["name", "toy"])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

## 10.Elimina nulos , considerando columnas especificas.

In [43]:
df.dropna(subset=["salario"])

    nombre        edad   salario    ciudad       fecha
0      Ana          25   15000.0  Culiacán  2024-01-15
1     Luis          32   22000.0  Mazatlán  2024/03/20
2     luis          32   22000.0  Mazatlán  2024/03/20
3   María   veintiocho   18500.0  culiacán  15-04-2024
4    Pedro         150  999999.0       NaN  2024-05-10
5      Ana          25   15000.0  Culiacán  2024-01-15

## 11.Cambio de tipos de datos  

Los datos importados llegan casi siempre como object. Convertir al tipo correcto reduce memoria, habilita operaciones y evita errores silenciosos.

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "nombre":    ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "edad":      ["25", "32", "28", "41", "36"],       # str
    "salario":   ["15,000", "22,000", "18,500", "31,000", "27,500"],  # str con coma
    "activo":    ["Sí", "No", "Sí", "Sí", "No"],      # bool como texto
    "depto":     ["TI", "RRHH", "TI", "Ventas", "RRHH"]  # categoría
})

print(df.dtypes)  #dtype object
print(df.memory_usage(deep=True))

nombre     str
edad       str
salario    str
activo     str
depto      str
dtype: object
Index      132
nombre     299
edad       255
salario    275
activo     303
depto      263
dtype: int64

In [3]:
df

  nombre edad salario activo   depto
0    Ana   25  15,000     Sí      TI
1   Luis   32  22,000     No    RRHH
2  María   28  18,500     Sí      TI
3  Pedro   41  31,000     Sí  Ventas
4  Sofía   36  27,500     No    RRHH

## 12. Entero: quitar coma de miles y convertir

In [4]:

df["edad"]    = df["edad"].astype("int8")     
df["salario"] = (df["salario"]
                  .str.replace(",", "")
                  .astype("int32"))

In [5]:
df

  nombre  edad  salario activo   depto
0    Ana    25    15000     Sí      TI
1   Luis    32    22000     No    RRHH
2  María    28    18500     Sí      TI
3  Pedro    41    31000     Sí  Ventas
4  Sofía    36    27500     No    RRHH

## 13. Booleano: mapear texto → True/False

In [6]:
# 
df["activo"] = df["activo"].map({"Sí": True, "No": False})

## 14. Categoría: columnas con pocos valores únicos

In [7]:

df["depto"] = df["depto"].astype("category") #Solo pandas

## 15. Verificar y comparar uso de memoria

In [66]:

print(df.dtypes)
print(df.memory_usage(deep=True))

nombre          str
edad           int8
salario       int32
activo       object
depto      category
dtype: object
Index      132
nombre     299
edad         5
salario     20
activo     160
depto      164
dtype: int64

In [8]:
df

  nombre  edad  salario  activo   depto
0    Ana    25    15000    True      TI
1   Luis    32    22000   False    RRHH
2  María    28    18500    True      TI
3  Pedro    41    31000    True  Ventas
4  Sofía    36    27500   False    RRHH

## 16. Manejo de fechas con pandas

In [9]:
import pandas as pd
import numpy as np

# Crear una fecha
fecha = pd.Timestamp("2026-05-17")
print(fecha)  # 2026-05-17 00:00:00

# Convertir string a datetime
df = pd.DataFrame({
    "fecha": ["2026-01-15", "2026-03-22", "2026-07-04"],
    "ventas": [150, 230, 310]
})

df["fecha"] = pd.to_datetime(df["fecha"])
print(df.dtypes)

2026-05-17 00:00:00
fecha     datetime64[us]
ventas             int64
dtype: object

## 17. Extraer componentes de fechas

In [10]:
df["año"]      = df["fecha"].dt.year
df["mes"]      = df["fecha"].dt.month
df["dia"]      = df["fecha"].dt.day
df["trimestre"]= df["fecha"].dt.quarter
df["dia_semana"]= df["fecha"].dt.day_name()   # 'Monday', 'Tuesday'...
df["semana"]   = df["fecha"].dt.isocalendar().week

print(df)

       fecha  ventas   año  mes  dia  trimestre dia_semana  semana
0 2026-01-15     150  2026    1   15          1   Thursday       3
1 2026-03-22     230  2026    3   22          1     Sunday      12
2 2026-07-04     310  2026    7    4          3   Saturday      27

## 18. Rangos de fechas

In [11]:
# Rango diario
rango_diario = pd.date_range(start="2026-01-01", end="2026-01-10", freq="D")

# Rango mensual
rango_mensual = pd.date_range(start="2026-01-01", periods=12, freq="MS")  # inicio de mes

# Rango de días hábiles
dias_habiles = pd.date_range(start="2026-01-01", periods=10, freq="B")

In [14]:
dias_habiles

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-05', '2026-01-06',
               '2026-01-07', '2026-01-08', '2026-01-09', '2026-01-12',
               '2026-01-13', '2026-01-14'],
              dtype='datetime64[us]', freq='B')

## 19. Fecuencias comunes.

![descripción](fechas.png)

## 20.Filtrar por fechas

In [15]:
# Filtrar por rango
mask = (df["fecha"] >= "2026-02-01") & (df["fecha"] <= "2026-06-30")
df_filtrado = df[mask]

# Filtrar por mes o año
df[df["fecha"].dt.month == 3]       # solo marzo
df[df["fecha"].dt.year == 2026]     # solo 2026

       fecha  ventas   año  mes  dia  trimestre dia_semana  semana
0 2026-01-15     150  2026    1   15          1   Thursday       3
1 2026-03-22     230  2026    3   22          1     Sunday      12
2 2026-07-04     310  2026    7    4          3   Saturday      27

## 21.Limpieza y normalización de texto con pandas  
La **limpieza y normalización de texto con pandas** consiste en preparar datos textuales para que sean consistentes, analizables y útiles en procesos como análisis de datos, minería de texto, machine learning o ETL. En muchos conjuntos de datos, el texto viene con problemas como:

Mayúsculas y minúsculas mezcladas
Espacios innecesarios
Acentos
Caracteres especiales
Errores de escritura
Diferentes formas de escribir lo mismo
Valores nulos

Con pandas se utilizan principalmente las funciones de la serie .str para transformar y limpiar cadenas.

In [16]:
import pandas as pd

df = pd.DataFrame({
    "nombre": ["  Juan PÉREZ ", "ana lópez", "CARLOS García  ", "  maría MARTÍNEZ"]
})

df["nombre_limpio"] = (df["nombre"]
    .str.strip()           # quitar espacios al inicio y final
    .str.lower()           # todo a minúsculas
    .str.title()           # Primera letra en mayúscula por palabra
)

print(df)

             nombre   nombre_limpio
0       Juan PÉREZ       Juan Pérez
1         ana lópez       Ana López
2   CARLOS García     Carlos García
3    maría MARTÍNEZ  María Martínez

## 22. Eliminar caracteres especiales y símbolos

In [17]:
df = pd.DataFrame({
    "descripcion": [
        "Servidor@Dell#2024!",
        "Switch   Cisco  24p",
        "Router//Mikrotik--RB",
        "UPS$APC***1500VA"
    ]
})

# Quitar todo excepto letras, números y espacios
df["desc_limpia"] = df["descripcion"].str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)

# Colapsar espacios múltiples en uno solo
df["desc_limpia"] = df["desc_limpia"].str.replace(r"\s+", " ", regex=True).str.strip()

print(df)

            descripcion       desc_limpia
0   Servidor@Dell#2024!  ServidorDell2024
1   Switch   Cisco  24p  Switch Cisco 24p
2  Router//Mikrotik--RB  RouterMikrotikRB
3      UPS$APC***1500VA      UPSAPC1500VA

## 23. Normalizar acentos y caracteres Unicode

In [18]:
import unicodedata

def quitar_acentos(texto):
    if pd.isna(texto):
        return texto
    return unicodedata.normalize("NFD", texto)\
                      .encode("ascii", "ignore")\
                      .decode("utf-8")

df = pd.DataFrame({
    "ciudad": ["Culiacán", "Mérida", "Guadalajara", "Querétaro", "León"]
})

df["ciudad_sin_acento"] = df["ciudad"].apply(quitar_acentos)

print(df)

        ciudad ciudad_sin_acento
0     Culiacán          Culiacan
1       Mérida            Merida
2  Guadalajara       Guadalajara
3    Querétaro         Queretaro
4         León              Leon

## 24. Estandarizar formatos: teléfonos

In [27]:
df = pd.DataFrame({
    "telefono": [
        "667-123-4567",
        "(667) 123 4567",
        "6671234567",
        "+52 667 123 4567",
        "667.123.4567"
    ]
})

# Quedarse solo con dígitos
df["solo_digitos"] = df["telefono"].str.replace(r"\D", "", regex=True)

# Tomar los últimos 10 dígitos (quitar lada internacional)
df["telefono_std"] = df["solo_digitos"].str[-10:]

# Formato uniforme: XXX-XXX-XXXX
df["telefono_fmt"] = df["telefono_std"].str.replace(
    r"(\d{3})(\d{3})(\d{4})", r"\1-\2-\3", regex=True
)

print(df[["telefono", "telefono_fmt"]])

           telefono  telefono_fmt
0      667-123-4567  667-123-4567
1    (667) 123 4567  667-123-4567
2        6671234567  667-123-4567
3  +52 667 123 4567  667-123-4567
4      667.123.4567  667-123-4567

# 25. Estandarizar correos electrónicos

In [31]:
df = pd.DataFrame({
    "correo": [
        "  Juan.Perez@UAS.EDU.MX  ",
        "ANA.LOPEZ@gmail.com",
        "carlos@EMPRESA.com.mx ",
        "MARIA@outlook.COM"
    ]
})

df["correo_std"] = (df["correo"]
    .str.strip()
    .str.lower()
)

# Validar formato básico con regex
df["es_valido"] = df["correo_std"].str.match(r"^[\w\.\-]+@[\w\-]+\.[a-z]{2,}(\.[a-z]{2,})?$")

print(df)

                      correo             correo_std  es_valido
0    Juan.Perez@UAS.EDU.MX    juan.perez@uas.edu.mx       True
1        ANA.LOPEZ@gmail.com    ana.lopez@gmail.com       True
2     carlos@EMPRESA.com.mx   carlos@empresa.com.mx       True
3          MARIA@outlook.COM      maria@outlook.com       True

## 26. Estandarizar categorías con variantes

In [32]:
df = pd.DataFrame({
    "departamento": [
        "Sistemas", "sistemas", "SISTEMAS", "Sis.",
        "Redes", "redes", "REDES",
        "Soporte", "soporte técnico", "Soporte Tecnico"
    ]
})

# Mapa de normalización
mapa = {
    r"sis.*":      "Sistemas",
    r"red.*":      "Redes",
    r"sop.*":      "Soporte",
}

def normalizar_dept(valor):
    valor_lower = str(valor).lower().strip()
    for patron, estandar in mapa.items():
        if pd.Series([valor_lower]).str.match(patron, case=False)[0]:
            return estandar
    return valor  # sin cambios si no hay coincidencia

df["dept_std"] = df["departamento"].apply(normalizar_dept)
print(df)

      departamento  dept_std
0         Sistemas  Sistemas
1         sistemas  Sistemas
2         SISTEMAS  Sistemas
3             Sis.  Sistemas
4            Redes     Redes
5            redes     Redes
6            REDES     Redes
7          Soporte   Soporte
8  soporte técnico   Soporte
9  Soporte Tecnico   Soporte

## 27. Extraer información con patrones

In [33]:
df = pd.DataFrame({
    "log": [
        "ERROR 2026-05-17 192.168.1.10 Disco lleno",
        "WARN  2026-05-16 10.0.0.5 CPU al 95%",
        "INFO  2026-05-15 172.16.0.1 Backup completado",
    ]
})

# Extraer campos por patrón
extraido = df["log"].str.extract(
    r"(?P<nivel>\w+)\s+(?P<fecha>\d{4}-\d{2}-\d{2})\s+(?P<ip>[\d.]+)\s+(?P<mensaje>.+)"
)

print(extraido)

   nivel       fecha            ip            mensaje
0  ERROR  2026-05-17  192.168.1.10        Disco lleno
1   WARN  2026-05-16      10.0.0.5         CPU al 95%
2   INFO  2026-05-15    172.16.0.1  Backup completado

## 28. Pipeline completo de limpieza

In [39]:
data = {
    "nombre":  ["Ana", "Luis", "   luis  ", " María7 ", "Pedro", "Ana", "sofía"],
    "edad":    [25, 32, 32, "veintiocho", 150, 25, np.nan],
    "salario": [15000, 22000, 22000, 18500, 999999, 15000, np.nan],
    "ciudad":  ["Culiacán", "Mazatlán", "Mazatlán", "culiacán", np.nan, "Culiacán", "Los Mochis"],
    "fecha":   ["2024-01-15", "2024/03/20", "2024/03/20", "15-04-2024", "2024-05-10", "2024-01-15", "2024-06-01"],
}

df = pd.DataFrame(data)

def limpiar_texto(serie: pd.Series) -> pd.Series:
    return (serie
        .astype(str)                                        # asegurar tipo string
        .str.strip()                                        # quitar espacios extremos
        .str.lower()                                        # minúsculas
        .str.replace(r"\s+", " ", regex=True)              # espacios múltiples
        .str.replace(r"[^a-záéíóúüñ\s0-9]", "", regex=True)  # solo letras/números
        .str.normalize("NFC")                               # normalizar unicode
    )

df["nombre_final"] = limpiar_texto(df["nombre"])

In [37]:
df

    nombre        edad   salario      ciudad       fecha nombre_final
0      Ana          25   15000.0    Culiacán  2024-01-15          ana
1     Luis          32   22000.0    Mazatlán  2024/03/20         luis
2     luis          32   22000.0    Mazatlán  2024/03/20         luis
3   María   veintiocho   18500.0    culiacán  15-04-2024        maría
4    Pedro         150  999999.0         NaN  2024-05-10        pedro
5      Ana          25   15000.0    Culiacán  2024-01-15          ana
6    sofía         NaN       NaN  Los Mochis  2024-06-01        sofía

## Normalización min–max y z-score

Normalizar datos significa transformar los valores de una columna para que estén en una escala común, sin que pierdan su relación entre sí.
El problema que resuelve es este: si tienes una columna de edades (25–45) y otra de salarios (15,000–80,000), la columna de salarios domina cualquier cálculo simplemente por tener números más grandes, aunque no sea más importante. Normalizar pone ambas columnas en el mismo nivel.

## Min-Max — comprime todos los valores al rango [0, 1]:  
valor normalizado = (x - mínimo) / (máximo - mínimo)  
El valor más pequeño siempre queda en 0, el más grande en 1, y todos los demás proporcionales entre ellos.  
  
Salarios:   15,000 → 0.0  
          22,000 → 0.44  
          31,000 → 1.0

## Z-score — transforma los valores para que la columna tenga media 0 y desviación estándar

![imagen](zscore.png)