## 1. Cargar los datos.

In [18]:
import pandas as pd
import numpy as np

data = {
    "nombre":  ["Ana", "Luis", "luis", " María ", "Pedro", "Ana", "sofía"],
    "edad":    [25, 32, 32, "veintiocho", 150, 25, np.nan],
    "salario": [15000, 22000, 22000, 18500, 999999, 15000, np.nan],
    "ciudad":  ["Culiacán", "Mazatlán", "Mazatlán", "culiacán", np.nan, "Culiacán", "Los Mochis"],
    "fecha":   ["2024-01-15", "2024/03/20", "2024/03/20", "15-04-2024", "2024-05-10", "2024-01-15", "2024-06-01"],
}

df = pd.DataFrame(data)
print(df)
print("\nInfo general:")
print(df.info())

    nombre        edad   salario      ciudad       fecha
0      Ana          25   15000.0    Culiacán  2024-01-15
1     Luis          32   22000.0    Mazatlán  2024/03/20
2     luis          32   22000.0    Mazatlán  2024/03/20
3   María   veintiocho   18500.0    culiacán  15-04-2024
4    Pedro         150  999999.0         NaN  2024-05-10
5      Ana          25   15000.0    Culiacán  2024-01-15
6    sofía         NaN       NaN  Los Mochis  2024-06-01

Info general:
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nombre   7 non-null      str
 1   edad     6 non-null      object
 2   salario  6 non-null      float64
 3   ciudad   6 non-null      str
 4   fecha    7 non-null      str
dtypes: float64(1), object(1), str(3)
memory usage: 412.0+ bytes
None

In [19]:
df

    nombre        edad   salario      ciudad       fecha
0      Ana          25   15000.0    Culiacán  2024-01-15
1     Luis          32   22000.0    Mazatlán  2024/03/20
2     luis          32   22000.0    Mazatlán  2024/03/20
3   María   veintiocho   18500.0    culiacán  15-04-2024
4    Pedro         150  999999.0         NaN  2024-05-10
5      Ana          25   15000.0    Culiacán  2024-01-15
6    sofía         NaN       NaN  Los Mochis  2024-06-01

In [ ]:
Limpieza de datos
Duplicados
Manejo de valores nulos
Correcciones de errores en datos

## 2. Duplicados

In [20]:
print("Duplicados encontrados:", df.duplicated().sum())
print(df[df.duplicated(keep=False)])  # muestra todos los duplicados

Duplicados encontrados: 1
  nombre edad  salario    ciudad       fecha
0    Ana   25  15000.0  Culiacán  2024-01-15
5    Ana   25  15000.0  Culiacán  2024-01-15

## 3. Eliminar duplicados (conserva el primero)

In [22]:
df_clean = df.drop_duplicates()

## 4. Duplicados parciales: mismo nombre sin importar mayúsculas.

Normalizar nombre , Unificar mayúsculas/minúsculas — decidir una convención y aplicarla a todo:

.str.lower() → "ana" (útil para comparar)  
.str.upper() → "ANA"  
.str.title() → "Ana García" (la más legible para nombres)  
.str.capitalize() → "Ana garcía" (solo la primera letra del string)  
  
Colapsar espacios internos — "Luis  Alberto" (doble espacio) → "Luis Alberto" con .str.replace(r"\s+", " ", regex=True)

In [36]:


df_clean["nombre_norm"] = df_clean["nombre"].str.strip().str.lower()
dupes_nombre = df_clean.duplicated(subset="nombre_norm", keep=False)
print("\nDuplicados por nombre (normalizado):")
print(df_clean[dupes_nombre])

Duplicados por nombre (normalizado):
Empty DataFrame
Columns: [nombre, edad, salario, ciudad, fecha, nombre_norm]
Index: []

## 5.Eliminar duplicados parciales

In [37]:
df_clean = df_clean.drop_duplicates(subset="nombre_norm").drop(columns=["nombre_norm"])

print(f"\nFilas originales: {len(df)} → Después: {len(df_clean)}")

Filas originales: 7 → Después: 5

## 6.Imprime Nulos por columna

In [38]:
print(df.isnull().sum())          
print(df.isnull().sum().sum())

nombre     0
edad       1
salario    1
ciudad     1
fecha      0
dtype: int64
3

##  7.Ver filas con cualquier nulo

In [39]:
print(df[df.isnull().any(axis=1)])

  nombre edad   salario      ciudad       fecha
4  Pedro  150  999999.0         NaN  2024-05-10
6  sofía  NaN       NaN  Los Mochis  2024-06-01

## 8.Elimina filas con Nulos!

In [40]:
df_sin_nulos = df.dropna()

## 9.Ayuda para ver opciones

In [41]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: Axis = 0,
    how: AnyAll | lib.NoDefault = <no_default>,
    thresh: int | lib.NoDefault = <no_default>,
    subset: IndexLabel | AnyArrayLike | None = None,
    inplace: bool = False,
    ignore_index: bool = False
) -> DataFrame | None method of pandas.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or iterable of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "name": ["Alfred", "Batman", "Catwoman"],
    ...         "toy": [np.nan, "Batmobile", "Bullwhip"],
    ...         "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    ...     }
    ... )
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis="columns")
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how="all")
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=["name", "toy"])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

## 10.Elimina nulos , considerando columnas especificas.

In [43]:
df.dropna(subset=["salario"])

    nombre        edad   salario    ciudad       fecha
0      Ana          25   15000.0  Culiacán  2024-01-15
1     Luis          32   22000.0  Mazatlán  2024/03/20
2     luis          32   22000.0  Mazatlán  2024/03/20
3   María   veintiocho   18500.0  culiacán  15-04-2024
4    Pedro         150  999999.0       NaN  2024-05-10
5      Ana          25   15000.0  Culiacán  2024-01-15

## 11.Cambio de tipos de datos  

Los datos importados llegan casi siempre como object. Convertir al tipo correcto reduce memoria, habilita operaciones y evita errores silenciosos.

In [67]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "nombre":    ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "edad":      ["25", "32", "28", "41", "36"],       # str
    "salario":   ["15,000", "22,000", "18,500", "31,000", "27,500"],  # str con coma
    "activo":    ["Sí", "No", "Sí", "Sí", "No"],      # bool como texto
    "depto":     ["TI", "RRHH", "TI", "Ventas", "RRHH"]  # categoría
})

print(df.dtypes)  #dtype object
print(df.memory_usage(deep=True))

nombre     str
edad       str
salario    str
activo     str
depto      str
dtype: object
Index      132
nombre     299
edad       255
salario    275
activo     303
depto      263
dtype: int64

In [57]:
df

  nombre edad salario activo   depto
0    Ana   25  15,000     Sí      TI
1   Luis   32  22,000     No    RRHH
2  María   28  18,500     Sí      TI
3  Pedro   41  31,000     Sí  Ventas
4  Sofía   36  27,500     No    RRHH

## 12. Entero: quitar coma de miles y convertir

In [58]:

df["edad"]    = df["edad"].astype("int8")     
df["salario"] = (df["salario"]
                  .str.replace(",", "")
                  .astype("int32"))

In [59]:
df

  nombre  edad  salario activo   depto
0    Ana    25    15000     Sí      TI
1   Luis    32    22000     No    RRHH
2  María    28    18500     Sí      TI
3  Pedro    41    31000     Sí  Ventas
4  Sofía    36    27500     No    RRHH

## 13. Booleano: mapear texto → True/False

In [63]:
# 
df["activo"] = df["activo"].map({"Sí": True, "No": False})

## 14. Categoría: columnas con pocos valores únicos

In [64]:

df["depto"] = df["depto"].astype("category") #Solo pandas

## 15. Verificar y comparar uso de memoria

In [66]:

print(df.dtypes)
print(df.memory_usage(deep=True))

nombre          str
edad           int8
salario       int32
activo       object
depto      category
dtype: object
Index      132
nombre     299
edad         5
salario     20
activo     160
depto      164
dtype: int64